### ISSUE TITLE
Cannot install composer conflict

### ISSUE THREAD

**Issue by Coysh** [sjelfull/craft-dumper#1]
`vagrant@homestead:~$ composer require superbig/craft-dumper
Using version ^1.0 for superbig/craft-dumper
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for superbig/craft-dumper ^1.0 -> satisfiable by superbig/craft-dumper[1.0.0].
    - superbig/craft-dumper 1.0.0 requires craftcms/cms ^3.0.0-RC1 -> satisfiable by craftcms/cms[3.0.0-RC1, 3.0.0-RC10, 3.0.0-RC10.1, 3.0.0-RC11, 3.0.0-RC12, 3.0.0-RC13, 3.0.0-RC14, 3.0.0-RC2, 3.0.0-RC3, 3.0.0-RC4, 3.0.0-RC5, 3.0.0-RC6, 3.0.0-RC7, 3.0.0-RC7.1, 3.0.0-RC8, 3.0.0-RC9] but these conflict with your requirements or minimum-stability.

Installation failed, deleting ./composer.json.`

And my project composer.json
`{
    "name": "craftcms/craft",
    "description": "Craft CMS",
    "keywords": [
        "craft",
        "cms",
        "craftcms",
        "project"
    ],
    "license": "MIT",
    "homepage": "https://craftcms.com/",
    "type": "project",
    "support": {
        "email": "support@craftcms.com",
        "issues": "https://github.com/craftcms/cms/issues",
        "forum": "https://craftcms.stackexchange.com/",
        "source": "https://github.com/craftcms/cms",
        "docs": "https://craftcms.com/docs",
        "rss": "https://craftcms.com/changelog.rss"
    },
    "require": {
        "php": ">=7.0.0",
        "craftcms/cms": "3.0.0-RC14",
        "vlucas/phpdotenv": "^2.4.0",
        "nystudio107/craft-imageoptimize": "1.4.23"
    },
    "autoload": {
        "psr-4": {
            "modules\\": "modules/"
        }
    },
    "config": {
        "optimize-autoloader": true,
        "platform": {
            "php": "7.0"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@composer dump-autoload -o",
            "@php craft setup/welcome"
        ]
    }
}
`

**Comment by sjelfull** [comment]
Try adding `  "minimum-stability": "dev"`

**Comment by sjelfull** [comment]
@Coysh did it work for you?

**Comment by Coysh** [comment]
@sjelfull Yep - that worked fine. Thanks 👍
