### ISSUE TITLE
Calling unknown method: craft\web\twig\variables\CraftVariable::dumper()

### ISSUE THREAD

**Issue by Coysh** [sjelfull/craft-dumper#2]
Getting this error after installing via the plugin store

`{{ craft.dumper.dump(entry) }}`

Plugin is definitely installed
![image](https://user-images.githubusercontent.com/5764356/37534694-6e83db8c-293d-11e8-83d7-fd30d22cb31a.png)

**Comment by sjelfull** [comment]
Hehe, that is actually not my plugin. I have the same name, but did not realise there was one until I tried publishing it in the store.

**Comment by Coysh** [comment]
Ha well I feel stupid now.

**Comment by sjelfull** [comment]
No worries, we have all been there 😂
